DROP TABLE IF EXISTS OBJECT_REGISTRY;
DROP TABLE IF EXISTS ENUM_OBJECT_TYPE;

CREATE TABLE OBJECT_REGISTRY (
    ID INTEGER PRIMARY KEY,
    TYPE INTEGER REFERENCES ENUM_OBJECT_TYPE(ID),
    NAME TEXT NOT NULL,
    CRID INTEGER NOT NULL,
    CRDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ERDATE TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (TYPE) REFERENCES ENUM_OBJECT_TYPE(ID)
);

CREATE TABLE ENUM_OBJECT_TYPE (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL
);